#!/usr/bin/env bash

## General ---------------------------------------------------#
BSPDIR="$HOME/.config/bspwm"
## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Configurations --------------------------------------------#
bspc monitor -d 1 2 3 4 5 6
bspc config border_width 0
bspc config window_gap 45
bspc config split_ratio 0.50

bspc config focused_border_color "#a3be8c"
bspc config normal_border_color "#3b4252"
bspc config active_border_color "#b48ead"
bspc config presel_feedback_color "#fab2df"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#
# remove all rules first
bspc rule -r *:*
bspc rule -a Zathura state=tiled

# 1 > terminal
#bspc rule -a Alacritty desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a Firefox desktop='^2' follow=on focus=on
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a Emacs desktop='^4' follow=on focus=on

# 3 > files
declare -a files=(Pcmanfm Thunar)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done
## Autostart -------------------------------------------------#
killall -9 sxhkd dunst picom unclutter wireplumber

pipewire &
pipewire-pulse &
wireplumber &
brillo -S 60
sxhkd -c "$BSPDIR"/sxhkdrc &
$HOME/.fehbg &
xset r rate 200 60 &
mpd &
unclutter --hide-on-touch &
bash ~/.config/polybar/launch.sh --grayblocks
picom --config ~/.config/bspwm/picom.conf &
dunst -conf ~/.config/bspwm/dunstrc &
